Soal 1

NO.1 Identifikasi dan jelaskan tipe data apa saja yang ada pada dataframe, ada berapa kolom dan baris, serta informasi apa saja yang terkandung dalam data tersebut?

In [112]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

path_to_file = '/content/DATA ANGGOTA KOMPI 19 - Sheet1.csv'
df = pd.read_csv(path_to_file)

df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (Cm)
0,SC61901,Akmal Fa'iq Naufal,Teknik Elektro,60,175
1,SC61902,Atthaya Layla Zhafira Hilwana,Bisnis Digital,52,168
2,SC61903,Dicky Fadhillah Herlambang,Fisika,64,165
3,SC61904,Firda Kusumawardhani Hillal,Teknologi Informasi,49,152
4,SC61905,Irsyad Daffa Armmawadin,Manajemen,75,178
5,SC61906,Marcela Anggi Puspitasari,Akuntansi,48,154
6,SC61907,Aulia Putri,Informatika,42,155
7,SC61908,Ni Kadek Fortuna Dewi,Matematika,45,158
8,SC61909,Rahma Aulia Agustari,Akuntansi,42,159
9,SC61910,Shania Maharani,Akuntansi,48,156
10,SC61911,Muhammad Firzal Anugerah Perdana,Informatika,55,167
11,SC61912,Anis Naila Mashurrin,Matematika,48,160
12,SC61913,Diva Nabila Herisnan,Teknik Informatika,62,172
13,SC61914,I Made Surya Adi Palguna,Informatika,105,180
14,SC61915,Made Bayu Maha Krisna Siaka,Informatika,82,172
15,SC61916,Nabila Sukma Mardeny,Sistem Informasi Kelautan,53,158
16,SC61917,Rainata Maharani,Pendidikan Akuntansi,50,162
17,SC61918,Valentin Asman Lestari,Statistika,59,160
18,SC61919,Amin Fauzan,Kesehatan Masyarakat,70,175
19,SC61920,Calvin Adiwinata,Teknik Informatika,53,162
20,SC61921,Fitri Novita Sari,Matematika,60,160
21,SC61922,Masayu Rizka Arfiyunia,Sistem Informasi,75,170
22,SC61923,Niswah Nasyithah,Informatika,40,153
23,SC61924,Sintiya Ristiyani,Sains Data,48,158
24,SC61925,Zamzammaimatul Zalfa Laila,Matematika,48,165

In [113]:
#identifikasi dan jelaskan tipe data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No. Peserta        25 non-null     object
 1   Nama               25 non-null     object
 2   Jurusan            25 non-null     object
 3   Berat Badan (Kg)   25 non-null     int64
 4   Tinggi Badan (Cm)  25 non-null     int64
dtypes: int64(2), object(3)
memory usage: 1.1+ KB

NO.2 Hitunglah BMI setiap siswa dengan rumus BMI=Berat badan (kg)/(Tinggi Badan (m))^2

In [114]:
## rumus
# BMI=Berat badan (kg)/(Tinggi Badan (m))^2
df.rename(columns={'Tinggi Badan (Cm)': 'Tinggi Badan (m)'}, inplace=True)
df['Tinggi Badan (m)'] = df['Tinggi Badan (m)'] / 100
df['BMI'] = df['Berat Badan (Kg)'] / (df['Tinggi Badan (m)'] ** 2)

df

,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (m),BMI
0,SC61901,Akmal Fa'iq Naufal,Teknik Elektro,60,1.75,19.591837
1,SC61902,Atthaya Layla Zhafira Hilwana,Bisnis Digital,52,1.68,18.424036
2,SC61903,Dicky Fadhillah Herlambang,Fisika,64,1.65,23.507805
3,SC61904,Firda Kusumawardhani Hillal,Teknologi Informasi,49,1.52,21.208449
4,SC61905,Irsyad Daffa Armmawadin,Manajemen,75,1.78,23.671254
5,SC61906,Marcela Anggi Puspitasari,Akuntansi,48,1.54,20.239501
6,SC61907,Aulia Putri,Informatika,42,1.55,17.481790
7,SC61908,Ni Kadek Fortuna Dewi,Matematika,45,1.58,18.025957
8,SC61909,Rahma Aulia Agustari,Akuntansi,42,1.59,16.613267
9,SC61910,Shania Maharani,Akuntansi,48,1.56,19.723866
10,SC61911,Muhammad Firzal Anugerah Perdana,Informatika,55,1.67,19.721037
11,SC61912,Anis Naila Mashurrin,Matematika,48,1.60,18.750000
12,SC61913,Diva Nabila Herisnan,Teknik Informatika,62,1.72,20.957274
13,SC61914,I Made Surya Adi Palguna,Informatika,105,1.80,32.407407
14,SC61915,Made Bayu Maha Krisna Siaka,Informatika,82,1.72,27.717685
15,SC61916,Nabila Sukma Mardeny,Sistem Informasi Kelautan,53,1.58,21.230572
16,SC61917,Rainata Maharani,Pendidikan Akuntansi,50,1.62,19.051974
17,SC61918,Valentin Asman Lestari,Statistika,59,1.60,23.046875
18,SC61919,Amin Fauzan,Kesehatan Masyarakat,70,1.75,22.857143
19,SC61920,Calvin Adiwinata,Teknik Informatika,53,1.62,20.195092
20,SC61921,Fitri Novita Sari,Matematika,60,1.60,23.437500
21,SC61922,Masayu Rizka Arfiyunia,Sistem Informasi,75,1.70,25.951557
22,SC61923,Niswah Nasyithah,Informatika,40,1.53,17.087445
23,SC61924,Sintiya Ristiyani,Sains Data,48,1.58,19.227688
24,SC61925,Zamzammaimatul Zalfa Laila,Matematika,48,1.65,17.630854

NO.3 Buatlah program untuk menghitung BMI

In [115]:
def determine_bmi_status(row):
    bmi_value = row['BMI']

    if bmi_value < 18.5:
        return 'Underweight'
    elif 18.5 <= bmi_value <= 24.9:
        return 'Normal'
    elif 25.0 <= bmi_value <= 29.9:
        return 'Overweight'
    elif 30.0 <= bmi_value <= 34.9:
        return 'Obesity'

df['Status BMI'] = df.apply(lambda row: determine_bmi_status(row), axis=1)

NO.4 Update dataframe df dengan menambahkan hasil perhitungan soal nomor 2, beri nama kolom BMI.

In [116]:
df

,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (m),BMI,Status BMI
0,SC61901,Akmal Fa'iq Naufal,Teknik Elektro,60,1.75,19.591837,Normal
1,SC61902,Atthaya Layla Zhafira Hilwana,Bisnis Digital,52,1.68,18.424036,Underweight
2,SC61903,Dicky Fadhillah Herlambang,Fisika,64,1.65,23.507805,Normal
3,SC61904,Firda Kusumawardhani Hillal,Teknologi Informasi,49,1.52,21.208449,Normal
4,SC61905,Irsyad Daffa Armmawadin,Manajemen,75,1.78,23.671254,Normal
5,SC61906,Marcela Anggi Puspitasari,Akuntansi,48,1.54,20.239501,Normal
6,SC61907,Aulia Putri,Informatika,42,1.55,17.481790,Underweight
7,SC61908,Ni Kadek Fortuna Dewi,Matematika,45,1.58,18.025957,Underweight
8,SC61909,Rahma Aulia Agustari,Akuntansi,42,1.59,16.613267,Underweight
9,SC61910,Shania Maharani,Akuntansi,48,1.56,19.723866,Normal
10,SC61911,Muhammad Firzal Anugerah Perdana,Informatika,55,1.67,19.721037,Normal
11,SC61912,Anis Naila Mashurrin,Matematika,48,1.60,18.750000,Normal
12,SC61913,Diva Nabila Herisnan,Teknik Informatika,62,1.72,20.957274,Normal
13,SC61914,I Made Surya Adi Palguna,Informatika,105,1.80,32.407407,Obesity
14,SC61915,Made Bayu Maha Krisna Siaka,Informatika,82,1.72,27.717685,Overweight
15,SC61916,Nabila Sukma Mardeny,Sistem Informasi Kelautan,53,1.58,21.230572,Normal
16,SC61917,Rainata Maharani,Pendidikan Akuntansi,50,1.62,19.051974,Normal
17,SC61918,Valentin Asman Lestari,Statistika,59,1.60,23.046875,Normal
18,SC61919,Amin Fauzan,Kesehatan Masyarakat,70,1.75,22.857143,Normal
19,SC61920,Calvin Adiwinata,Teknik Informatika,53,1.62,20.195092,Normal
20,SC61921,Fitri Novita Sari,Matematika,60,1.60,23.437500,Normal
21,SC61922,Masayu Rizka Arfiyunia,Sistem Informasi,75,1.70,25.951557,Overweight
22,SC61923,Niswah Nasyithah,Informatika,40,1.53,17.087445,Underweight
23,SC61924,Sintiya Ristiyani,Sains Data,48,1.58,19.227688,Normal
24,SC61925,Zamzammaimatul Zalfa Laila,Matematika,48,1.65,17.630854,Underweight

NO.5 Buatlah status BMI untuk setiap siswa dari kategori berikut, lalu simpan data statusnya dengan nama kolom Status BMI.

-Normal: 18.5-24.9

-Overweight: 25.0-29.9

-Obesity: 30.0-34.9

-Underweight: < 18.5

In [117]:
def determine_bmi_status(row):
    bmi_value = row['BMI']

    if bmi_value < 18.5:
        return 'Underweight'
    elif 18.5 <= bmi_value <= 24.9:
        return 'Normal'
    elif 25.0 <= bmi_value <= 29.9:
        return 'Overweight'
    elif 30.0 <= bmi_value <= 34.9:
        return 'Obesity'


df['Status BMI'] = df.apply(lambda row: determine_bmi_status(row), axis=1)

In [118]:
df

,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (m),BMI,Status BMI
0,SC61901,Akmal Fa'iq Naufal,Teknik Elektro,60,1.75,19.591837,Normal
1,SC61902,Atthaya Layla Zhafira Hilwana,Bisnis Digital,52,1.68,18.424036,Underweight
2,SC61903,Dicky Fadhillah Herlambang,Fisika,64,1.65,23.507805,Normal
3,SC61904,Firda Kusumawardhani Hillal,Teknologi Informasi,49,1.52,21.208449,Normal
4,SC61905,Irsyad Daffa Armmawadin,Manajemen,75,1.78,23.671254,Normal
5,SC61906,Marcela Anggi Puspitasari,Akuntansi,48,1.54,20.239501,Normal
6,SC61907,Aulia Putri,Informatika,42,1.55,17.481790,Underweight
7,SC61908,Ni Kadek Fortuna Dewi,Matematika,45,1.58,18.025957,Underweight
8,SC61909,Rahma Aulia Agustari,Akuntansi,42,1.59,16.613267,Underweight
9,SC61910,Shania Maharani,Akuntansi,48,1.56,19.723866,Normal
10,SC61911,Muhammad Firzal Anugerah Perdana,Informatika,55,1.67,19.721037,Normal
11,SC61912,Anis Naila Mashurrin,Matematika,48,1.60,18.750000,Normal
12,SC61913,Diva Nabila Herisnan,Teknik Informatika,62,1.72,20.957274,Normal
13,SC61914,I Made Surya Adi Palguna,Informatika,105,1.80,32.407407,Obesity
14,SC61915,Made Bayu Maha Krisna Siaka,Informatika,82,1.72,27.717685,Overweight
15,SC61916,Nabila Sukma Mardeny,Sistem Informasi Kelautan,53,1.58,21.230572,Normal
16,SC61917,Rainata Maharani,Pendidikan Akuntansi,50,1.62,19.051974,Normal
17,SC61918,Valentin Asman Lestari,Statistika,59,1.60,23.046875,Normal
18,SC61919,Amin Fauzan,Kesehatan Masyarakat,70,1.75,22.857143,Normal
19,SC61920,Calvin Adiwinata,Teknik Informatika,53,1.62,20.195092,Normal
20,SC61921,Fitri Novita Sari,Matematika,60,1.60,23.437500,Normal
21,SC61922,Masayu Rizka Arfiyunia,Sistem Informasi,75,1.70,25.951557,Overweight
22,SC61923,Niswah Nasyithah,Informatika,40,1.53,17.087445,Underweight
23,SC61924,Sintiya Ristiyani,Sains Data,48,1.58,19.227688,Normal
24,SC61925,Zamzammaimatul Zalfa Laila,Matematika,48,1.65,17.630854,Underweight

NO.6 a. Buatlah variabel baru lalu urutkan data berdasarkan tinggi badan dari yang tertinggi ke rendah.

b. Buat variabel baru lalu urutkan data berdasarkan Nama dari Z – A.

In [119]:
# a
urutan_tinggi = df.sort_values(by ='Tinggi Badan (m)', ascending = False)
urutan_tinggi

#b
urutan_nama_descending = df.sort_values(by ='Nama', ascending = False)
urutan_nama_descending

,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (m),BMI,Status BMI
24,SC61925,Zamzammaimatul Zalfa Laila,Matematika,48,1.65,17.630854,Underweight
17,SC61918,Valentin Asman Lestari,Statistika,59,1.60,23.046875,Normal
23,SC61924,Sintiya Ristiyani,Sains Data,48,1.58,19.227688,Normal
9,SC61910,Shania Maharani,Akuntansi,48,1.56,19.723866,Normal
16,SC61917,Rainata Maharani,Pendidikan Akuntansi,50,1.62,19.051974,Normal
8,SC61909,Rahma Aulia Agustari,Akuntansi,42,1.59,16.613267,Underweight
22,SC61923,Niswah Nasyithah,Informatika,40,1.53,17.087445,Underweight
7,SC61908,Ni Kadek Fortuna Dewi,Matematika,45,1.58,18.025957,Underweight
15,SC61916,Nabila Sukma Mardeny,Sistem Informasi Kelautan,53,1.58,21.230572,Normal
10,SC61911,Muhammad Firzal Anugerah Perdana,Informatika,55,1.67,19.721037,Normal
21,SC61922,Masayu Rizka Arfiyunia,Sistem Informasi,75,1.70,25.951557,Overweight
5,SC61906,Marcela Anggi Puspitasari,Akuntansi,48,1.54,20.239501,Normal
14,SC61915,Made Bayu Maha Krisna Siaka,Informatika,82,1.72,27.717685,Overweight
4,SC61905,Irsyad Daffa Armmawadin,Manajemen,75,1.78,23.671254,Normal
13,SC61914,I Made Surya Adi Palguna,Informatika,105,1.80,32.407407,Obesity
20,SC61921,Fitri Novita Sari,Matematika,60,1.60,23.437500,Normal
3,SC61904,Firda Kusumawardhani Hillal,Teknologi Informasi,49,1.52,21.208449,Normal
12,SC61913,Diva Nabila Herisnan,Teknik Informatika,62,1.72,20.957274,Normal
2,SC61903,Dicky Fadhillah Herlambang,Fisika,64,1.65,23.507805,Normal
19,SC61920,Calvin Adiwinata,Teknik Informatika,53,1.62,20.195092,Normal
6,SC61907,Aulia Putri,Informatika,42,1.55,17.481790,Underweight
1,SC61902,Atthaya Layla Zhafira Hilwana,Bisnis Digital,52,1.68,18.424036,Underweight
11,SC61912,Anis Naila Mashurrin,Matematika,48,1.60,18.750000,Normal
18,SC61919,Amin Fauzan,Kesehatan Masyarakat,70,1.75,22.857143,Normal
0,SC61901,Akmal Fa'iq Naufal,Teknik Elektro,60,1.75,19.591837,Normal

NO.7 Filter dataframe df berdasarkan:

a. Status BMI di luar Normal.

b. Tinggi Badan > 169 cm dan Berat Badan > 60 kg

c. Nama yang mengandung huruf “y”.

d. Siapa saja yang berat badannya kurang dari 60 kg?

In [120]:
# a. filter status BMI di luar normal
filter_a = df[df['Status BMI']!= 'Normal']
filter_a

,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (m),BMI,Status BMI
1,SC61902,Atthaya Layla Zhafira Hilwana,Bisnis Digital,52,1.68,18.424036,Underweight
6,SC61907,Aulia Putri,Informatika,42,1.55,17.481790,Underweight
7,SC61908,Ni Kadek Fortuna Dewi,Matematika,45,1.58,18.025957,Underweight
8,SC61909,Rahma Aulia Agustari,Akuntansi,42,1.59,16.613267,Underweight
13,SC61914,I Made Surya Adi Palguna,Informatika,105,1.80,32.407407,Obesity
14,SC61915,Made Bayu Maha Krisna Siaka,Informatika,82,1.72,27.717685,Overweight
21,SC61922,Masayu Rizka Arfiyunia,Sistem Informasi,75,1.70,25.951557,Overweight
22,SC61923,Niswah Nasyithah,Informatika,40,1.53,17.087445,Underweight
24,SC61925,Zamzammaimatul Zalfa Laila,Matematika,48,1.65,17.630854,Underweight

In [121]:
# b. Tinggi Badan > 169 cm dan Berat Badan > 60 kg
filter_b = df[(df['Tinggi Badan (m)'] > 1.69) & (df['Berat Badan (Kg)'] > 60)]
filter_b

,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (m),BMI,Status BMI
4,SC61905,Irsyad Daffa Armmawadin,Manajemen,75,1.78,23.671254,Normal
12,SC61913,Diva Nabila Herisnan,Teknik Informatika,62,1.72,20.957274,Normal
13,SC61914,I Made Surya Adi Palguna,Informatika,105,1.80,32.407407,Obesity
14,SC61915,Made Bayu Maha Krisna Siaka,Informatika,82,1.72,27.717685,Overweight
18,SC61919,Amin Fauzan,Kesehatan Masyarakat,70,1.75,22.857143,Normal
21,SC61922,Masayu Rizka Arfiyunia,Sistem Informasi,75,1.70,25.951557,Overweight

In [122]:
# c. Nama yang mengandung huruf “y”
filter_c = df[df['Nama'].str.contains('y', case=False)]
filter_c

,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (m),BMI,Status BMI
1,SC61902,Atthaya Layla Zhafira Hilwana,Bisnis Digital,52,1.68,18.424036,Underweight
2,SC61903,Dicky Fadhillah Herlambang,Fisika,64,1.65,23.507805,Normal
4,SC61905,Irsyad Daffa Armmawadin,Manajemen,75,1.78,23.671254,Normal
13,SC61914,I Made Surya Adi Palguna,Informatika,105,1.80,32.407407,Obesity
14,SC61915,Made Bayu Maha Krisna Siaka,Informatika,82,1.72,27.717685,Overweight
15,SC61916,Nabila Sukma Mardeny,Sistem Informasi Kelautan,53,1.58,21.230572,Normal
21,SC61922,Masayu Rizka Arfiyunia,Sistem Informasi,75,1.70,25.951557,Overweight
22,SC61923,Niswah Nasyithah,Informatika,40,1.53,17.087445,Underweight
23,SC61924,Sintiya Ristiyani,Sains Data,48,1.58,19.227688,Normal

In [123]:
# d. Siapa saja yang berat badannya kurang dari 60 kg?
filter_d = df[df['Berat Badan (Kg)'] < 60]
filter_d

,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (m),BMI,Status BMI
1,SC61902,Atthaya Layla Zhafira Hilwana,Bisnis Digital,52,1.68,18.424036,Underweight
3,SC61904,Firda Kusumawardhani Hillal,Teknologi Informasi,49,1.52,21.208449,Normal
5,SC61906,Marcela Anggi Puspitasari,Akuntansi,48,1.54,20.239501,Normal
6,SC61907,Aulia Putri,Informatika,42,1.55,17.481790,Underweight
7,SC61908,Ni Kadek Fortuna Dewi,Matematika,45,1.58,18.025957,Underweight
8,SC61909,Rahma Aulia Agustari,Akuntansi,42,1.59,16.613267,Underweight
9,SC61910,Shania Maharani,Akuntansi,48,1.56,19.723866,Normal
10,SC61911,Muhammad Firzal Anugerah Perdana,Informatika,55,1.67,19.721037,Normal
11,SC61912,Anis Naila Mashurrin,Matematika,48,1.60,18.750000,Normal
15,SC61916,Nabila Sukma Mardeny,Sistem Informasi Kelautan,53,1.58,21.230572,Normal
16,SC61917,Rainata Maharani,Pendidikan Akuntansi,50,1.62,19.051974,Normal
17,SC61918,Valentin Asman Lestari,Statistika,59,1.60,23.046875,Normal
19,SC61920,Calvin Adiwinata,Teknik Informatika,53,1.62,20.195092,Normal
22,SC61923,Niswah Nasyithah,Informatika,40,1.53,17.087445,Underweight
23,SC61924,Sintiya Ristiyani,Sains Data,48,1.58,19.227688,Normal
24,SC61925,Zamzammaimatul Zalfa Laila,Matematika,48,1.65,17.630854,Underweight

NO.8 Tambahkan nomor urut pada dataframe df sesuai jumlah siswa dan tempatkan kolom nomor baru tersebut di paling ujung kiri sebagai kolom pertama serta beri nama kolomnya “No.”!

In [124]:
# Menambahkan kolom "No." sebagai nomor urut
df['No.'] = range(1, len(df) + 1)

# Menempatkan kolom "No." di paling kiri
df = df[['No.'] + [col for col in df.columns if col != 'No.']]

df

,No.,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (m),BMI,Status BMI
0,1,SC61901,Akmal Fa'iq Naufal,Teknik Elektro,60,1.75,19.591837,Normal
1,2,SC61902,Atthaya Layla Zhafira Hilwana,Bisnis Digital,52,1.68,18.424036,Underweight
2,3,SC61903,Dicky Fadhillah Herlambang,Fisika,64,1.65,23.507805,Normal
3,4,SC61904,Firda Kusumawardhani Hillal,Teknologi Informasi,49,1.52,21.208449,Normal
4,5,SC61905,Irsyad Daffa Armmawadin,Manajemen,75,1.78,23.671254,Normal
5,6,SC61906,Marcela Anggi Puspitasari,Akuntansi,48,1.54,20.239501,Normal
6,7,SC61907,Aulia Putri,Informatika,42,1.55,17.481790,Underweight
7,8,SC61908,Ni Kadek Fortuna Dewi,Matematika,45,1.58,18.025957,Underweight
8,9,SC61909,Rahma Aulia Agustari,Akuntansi,42,1.59,16.613267,Underweight
9,10,SC61910,Shania Maharani,Akuntansi,48,1.56,19.723866,Normal
10,11,SC61911,Muhammad Firzal Anugerah Perdana,Informatika,55,1.67,19.721037,Normal
11,12,SC61912,Anis Naila Mashurrin,Matematika,48,1.60,18.750000,Normal
12,13,SC61913,Diva Nabila Herisnan,Teknik Informatika,62,1.72,20.957274,Normal
13,14,SC61914,I Made Surya Adi Palguna,Informatika,105,1.80,32.407407,Obesity
14,15,SC61915,Made Bayu Maha Krisna Siaka,Informatika,82,1.72,27.717685,Overweight
15,16,SC61916,Nabila Sukma Mardeny,Sistem Informasi Kelautan,53,1.58,21.230572,Normal
16,17,SC61917,Rainata Maharani,Pendidikan Akuntansi,50,1.62,19.051974,Normal
17,18,SC61918,Valentin Asman Lestari,Statistika,59,1.60,23.046875,Normal
18,19,SC61919,Amin Fauzan,Kesehatan Masyarakat,70,1.75,22.857143,Normal
19,20,SC61920,Calvin Adiwinata,Teknik Informatika,53,1.62,20.195092,Normal
20,21,SC61921,Fitri Novita Sari,Matematika,60,1.60,23.437500,Normal
21,22,SC61922,Masayu Rizka Arfiyunia,Sistem Informasi,75,1.70,25.951557,Overweight
22,23,SC61923,Niswah Nasyithah,Informatika,40,1.53,17.087445,Underweight
23,24,SC61924,Sintiya Ristiyani,Sains Data,48,1.58,19.227688,Normal
24,25,SC61925,Zamzammaimatul Zalfa Laila,Matematika,48,1.65,17.630854,Underweight

Cari nilai-nilai berikut:

-Cari nilai terendah dan tertingginya.

-Berapa nilai rata-rata tinggi badan siswa?

-Berapa rata-rata berat badan siswa?

-Ada berapa orang jumlah siswa  yang tercatat pada dataframe df?

-5 orang dengan nilai BMI tertinggi.

-Ada berapa orang yang tergolong status Underweight, Normal, Overweight, dan Obesity?

In [125]:
# cari nilai terendah dan tertingginya
min_bmi = df['BMI'].min()
max_bmi = df['BMI'].max()

print("Nilai BMI Terendah:", min_bmi)
print("Nilai BMI Tertinggi:", max_bmi)

Nilai BMI Terendah: 16.61326688026581
Nilai BMI Tertinggi: 32.407407407407405

In [126]:
# Berapa nilai rata-rata tinggi badan siswa?
mean_height = df['Tinggi Badan (m)'].mean()

print("Rata-rata Tinggi Badan Siswa:", mean_height)

Rata-rata Tinggi Badan Siswa: 1.6376

In [127]:
# Berapa rata-rata berat badan siswa?
mean_weight = df['Berat Badan (Kg)'].mean()

print("Rata-rata Berat Badan Siswa:", mean_height)

Rata-rata Berat Badan Siswa: 1.6376

In [128]:
# Ada berapa orang jumlah siswa yang tercatat pada dataframe df?
total_students = len(df)

print("Jumlah Siswa:", total_students)

Jumlah Siswa: 25

In [129]:
# 5 orang dengan BMI tertinggi
top_5_bmi = df.nlargest(5, 'BMI')
df_top_5_bmi = top_5_bmi

df_top_5_bmi

,No.,No. Peserta,Nama,Jurusan,Berat Badan (Kg),Tinggi Badan (m),BMI,Status BMI
13,14,SC61914,I Made Surya Adi Palguna,Informatika,105,1.80,32.407407,Obesity
14,15,SC61915,Made Bayu Maha Krisna Siaka,Informatika,82,1.72,27.717685,Overweight
21,22,SC61922,Masayu Rizka Arfiyunia,Sistem Informasi,75,1.70,25.951557,Overweight
4,5,SC61905,Irsyad Daffa Armmawadin,Manajemen,75,1.78,23.671254,Normal
2,3,SC61903,Dicky Fadhillah Herlambang,Fisika,64,1.65,23.507805,Normal

In [130]:
# Ada berapa orang yang tergolong status Underweight, Normal, Overweight, dan Obesity?
status_count = df['Status BMI'].value_counts()

print("Jumlah Orang berdasarkan Status BMI:")
print(status_count)

Jumlah Orang berdasarkan Status BMI:
Normal         16
Underweight     6
Overweight      2
Obesity         1
Name: Status BMI, dtype: int64

# Soal 2
Perusahaan Invesitasi Jamin-Sugih CO kami memberikan penawaran invesitasi terbaik dengan pembagian keuntungan tetap sebesar 25% setiap tahun

---
Buatlah program Python yang dapat menerima input dari pengguna dalam bentuk :

---

1. Modal invesitasi (bilangan bulat antara 0 - 1000.000.000)
2. Jangka Waktu invesitasi (bilangan bulat antara 1-25 dalam tahun)


---
Selain itu, program akan menampilkan error message bahwa modal atau tenure tidak sesuai ketentuan


---
Program akan menampilkan informasi akumulasi invesitasi setiap tahun menggunakan iterasi untuk setiap tahun


---
contoh :

Input

Money Capita : 100000

Investment Tenure (years) : 2

Output

Year 1, your total investment : 125000.0

Year 2, yout total investment : 156250.0

In [131]:
#fungsi program
def investasi(capital, tenure):
    if (capital <= 0 or capital > 1000000000) or (tenure < 1 or tenure > 25):
        print("Error: Modal atau tenure tidak sesuai ketentuan.")
        return

    keuntungan_tahunan = 0.25
    total_investasi = capital

    for year in range(1, tenure + 1):
        total_investasi +=  total_investasi * keuntungan_tahunan
        print(f"Year {year}, your total investment : {total_investasi:.1f}")


# Input dari pengguna
try:
    capital = int(input("Money Capital : "))
    tenure = int(input("Investment Tenure (years) : "))
    investasi(capital, tenure)
except:
    print("Error: masukan angka dalam bentuk bilangan bulat.")

Money Capital : 10000000
Investment Tenure (years) : 13
Year 1, your total investment : 12500000.0
Year 2, your total investment : 15625000.0
Year 3, your total investment : 19531250.0
Year 4, your total investment : 24414062.5
Year 5, your total investment : 30517578.1
Year 6, your total investment : 38146972.7
Year 7, your total investment : 47683715.8
Year 8, your total investment : 59604644.8
Year 9, your total investment : 74505806.0
Year 10, your total investment : 93132257.5
Year 11, your total investment : 116415321.8
Year 12, your total investment : 145519152.3
Year 13, your total investment : 181898940.4